# Generated by Django 2.2.20 on 2021-09-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
