# Generated by Django 2.2.20 on 2021-09-14 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_image', '0002_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Famous',
        ),
    ]
