# Generated by Django 2.2.20 on 2021-09-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_image', '0004_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
