# Generated by Django 2.2.20 on 2021-09-23 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_image', '0006_auto_20210914_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famous',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
